### ISSUE TITLE
Metadata of the diff file could duplicate occasionally

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/materialstore#68]
```
2022-01-20 22:52:56.404 ERROR c.k.katalon.core.main.TestCaseExecutor   - ❌ Test Cases/main/Flaskr/VisualInspectionTwins FAILED.
Reason:
com.kazurayam.materialstore.MaterialstoreException: The combination of fileType=html and metadata={"category":"diff", "left":"611cb79bb6132c8966679e0e9e1fa203a119391f", "ratio":"3.45", "right":"871d38415b35dc72f6e60c9654ab67b3a51c486e"}is already there in the index
	at com.kazurayam.materialstore.Jobber.write(Jobber.groovy:161)
	at com.kazurayam.materialstore.Jobber$write.call(Unknown Source)
```

How to identify them?

**Comment by kazurayam** [comment]
The index file:

```
9435d8c206e3adc1310d160c059f7b114b1d54f3	html	{"URL.host":"127.0.0.1", "URL.path":"/", "URL.protocol":"http", "profile":"Flaskr_DevelopmentEnv", "step":"1"}
f4549aff5e21f7b554bbed80ddf214105d831b2d	png	{"URL.host":"127.0.0.1", "URL.path":"/", "URL.protocol":"http", "profile":"Flaskr_DevelopmentEnv", "step":"1"}
48535e6235eefad54c196fe225bdde0c017327c3	html	{"URL.host":"127.0.0.1", "URL.path":"/", "URL.protocol":"http", "profile":"Flaskr_DevelopmentEnv", "step":"2"}
8f0e83bd1d243ee0367560502e2b242b3a401608	png	{"URL.host":"127.0.0.1", "URL.path":"/", "URL.protocol":"http", "profile":"Flaskr_DevelopmentEnv", "step":"2"}
3e636ce65d3825679af88bb6fd544d648de71a58	html	{"URL.host":"127.0.0.1", "URL.path":"/", "URL.protocol":"http", "profile":"Flaskr_DevelopmentEnv", "step":"3"}
c177db625719db3eeea57a60c99c2cbbf3f7ba47	png	{"URL.host":"127.0.0.1", "URL.path":"/", "URL.protocol":"http", "profile":"Flaskr_DevelopmentEnv", "step":"3"}
871d38415b35dc72f6e60c9654ab67b3a51c486e	html	{"URL.host":"127.0.0.1", "URL.path":"/", "URL.protocol":"http", "profile":"Flaskr_DevelopmentEnv", "step":"4"}
cb0f622bce72eb7418fa12a8d59ac7c7795490ff	png	{"URL.host":"127.0.0.1", "URL.path":"/", "URL.protocol":"http", "profile":"Flaskr_DevelopmentEnv", "step":"4"}
871d38415b35dc72f6e60c9654ab67b3a51c486e	html	{"URL.host":"127.0.0.1", "URL.path":"/", "URL.protocol":"http", "profile":"Flaskr_DevelopmentEnv", "step":"5"}
85cbfedcb060806bcee75686b985443cc073f750	png	{"URL.host":"127.0.0.1", "URL.path":"/", "URL.protocol":"http", "profile":"Flaskr_DevelopmentEnv", "step":"5"}
070129d4a55b87af89afae9b04158570a23b70f5	html	{"URL.host":"127.0.0.1", "URL.path":"/", "URL.protocol":"http", "profile":"Flaskr_DevelopmentEnv", "step":"6"}
15506b73740ec85b57060358258f99de47c1c9af	png	{"URL.host":"127.0.0.1", "URL.path":"/", "URL.protocol":"http", "profile":"Flaskr_DevelopmentEnv", "step":"6"}
4ae770b442a672a3f0e9ab4145b83b41c870e403	html	{"category":"diff", "left":"17feefbce7cb3ec554fa5c3f5823705827007d8d", "ratio":"4.55", "right":"9435d8c206e3adc1310d160c059f7b114b1d54f3"}
a794f3f78b3bc946be07963eb15c167360771794	html	{"category":"diff", "left":"336a4399a662e57383052a89d9043a4b5fe5620e", "ratio":"3.45", "right":"48535e6235eefad54c196fe225bdde0c017327c3"}
10775e87eb1e960ed582c5ca23dee2a005f48f47	png	{"category":"diff", "left":"546929466ee2528d8dae0a6e971aa88e85c883a4", "ratio":"0.29", "right":"c177db625719db3eeea57a60c99c2cbbf3f7ba47"}
b007991324e303b0d85b6d89526158d20109e041	html	{"category":"diff", "left":"611cb79bb6132c8966679e0e9e1fa203a119391f", "ratio":"3.45", "right":"871d38415b35dc72f6e60c9654ab67b3a51c486e"}
3ffa0a6ece1201f1992a07b0b04973a783328b04	png	{"category":"diff", "left":"824f85a2a6a626417c1274f9220a0ce15d3fd939", "ratio":"0.29", "right":"8f0e83bd1d243ee0367560502e2b242b3a401608"}
51c6c4431e523bbbc23985df3a05245f60359337	png	{"category":"diff", "left":"be4f0c704cb47fd11fb4100c92779591952f4ab5", "ratio":"0.29", "right":"f4549aff5e21f7b554bbed80ddf214105d831b2d"}
f067047c1e032b8a76d01f56809be2a32256836e	html	{"category":"diff", "left":"c2a80e906350902d7768286bfc8f7df7ca74a7a7", "ratio":"3.45", "right":"3e636ce65d3825679af88bb6fd544d648de71a58"}
ff38125682178867d233581a6d8ffb9f894c0c2d	png	{"category":"diff", "left":"cb91ca521139d9bd5afbc95719ecdfe193fc5bb5", "ratio":"0.28", "right":"cb0f622bce72eb7418fa12a8d59ac7c7795490ff"}

```
